### ISSUE TITLE
hot key for script

### ISSUE THREAD

**Issue by ghost** [Gubaer/josm-scripting-plugin#24]
Hello I'm tagging very often building:levels. 15k until now. I takes very long, to do that much often.

My idea is to configure 9 hotkeys for adding the current selection the tag building:levels=1...9. The script behind should not be the problem, but how can i connect a hotkey directly to a script?

Regards Johannes

**Comment by bjohas** [comment]
We're also interested in this :)

It's of course also possible to set the hot keys manually. Once the action is defined, it's in the usual place in the preferences... but it would be good to be able to script it too.

**Comment by SwiftFast** [comment]
I offer a minimalist solution which is imperfect but works very well.

Designate special **temporary tags**, which are as short as possible to be your shortcuts, then use JOSM's built-in tag adding shortcuts, such as ALT+A (and the various shortcuts shown at the bottom of the tag add window) to quickly add the temporary tags to elements. Once you finish editing, run a script which replaces the temporary tags with the desired tags. The final result is much less typing.

For instance, if you choose to use this translation table...

```
a=1 > building:levels = 1, building=yes
a=2 > building:levels = 2, building=yes
...and so on...
```

... then this script should do the trick:

```javascript
var print = require("josm/util").println;
var cnt = 0; // how many shortcut tags were found

function main()
{
	print("");
	print("### Running script");
	var layer = josm.layers.get(0); // can also pass a string as layer name
	var ds = layer.data;
	ds.each(check); // for each element
	print("");
	print("### Script finished. Shortcut tags found: " + cnt);
}
main();
function check(p)
{
	if (p.tags["a"] !== undefined)
	{
		var level = p.tags["a"];
		p.tags["building:levels"] = level;
		p.tags["building"] = "yes";

		p.removeTag("a"); 
		cnt++;
		// warning, removeTag not present older Scripting Plugin versions.
		// update your version or see the workaround.
		// See https://github.com/Gubaer/josm-scripting-plugin/issues/42
	}
}
```

This can be extended quite nicely. With the `split` method you can even parse multiple parameters e.g. in order to achieve this...

```
a="burj khalifa,163" > building:levels = 163, building=yes, name="burj khalifa", name:en="burj khalifa".
```

... You can use this script:

```javascript
//main same as above
function check(p)
{
	if (p.tags["a"] !== undefined)
	{
		var array = p.tags["a"].split(",");
		var name = array[0];
		var levels = array[1];
		p.tags["building:levels"] = levels;
		p.tags["name"] = name;
		p.tags["name:en"] = name;
		p.tags["building"] = "yes";

		p.removeTag("a"); 
		cnt++;
		// warning, removeTag not present older Scripting Plugin versions.
		// update your version or see the workaround.
		// See https://github.com/Gubaer/josm-scripting-plugin/issues/42
	}
}
```

**Comment by SwiftFast** [comment]
Also, system-wide keyboard shortcuts such as TAB are your friends for maximum efficiency, they save you from moving around your cursor.
