### ISSUE TITLE
Mixin method name conflict causes problems with tag removal

### ISSUE THREAD

**Issue by SwiftFast** [Gubaer/josm-scripting-plugin#42]
[OsmPrimitiveMixin](https://gubaer.github.io/josm-scripting-plugin/apidoc/mixins/OsmPrimitiveMixin.html) has a `remove(tag)` method, which removes a tag.

[WayMixin](https://gubaer.github.io/josm-scripting-plugin/apidoc/mixins/WayMixin.html) has a `remove(node)` method, which removes a way from a node.

Since Ways use both of the above mixins, one cannot call the `OsmPrimitiveMixin` remove function, and one cannot remove tags from ways. The fix should be simple: Rename one of the methods.

In the meantime, I came up with this workaround:

```
var remove;
(function()
{
	var removeFunction;
	var builder= require("josm/builder");
	var nb = builder.NodeBuilder;
	var tempNode = nb.withPosition(10,10).create();
	removeFunction = tempNode.remove;
	remove = function remove(p, tag)
	{
		removeFunction.call(p, tag);
	}
})();

// now use remove(p, tag) rather than p.remove(tag)

```

**Comment by Gubaer** [comment]
On both a node and a way you can now use `removeTag(key)` to remove a tag. The former method `remove(key)` is still supported, but deprecated, because it doesn't work on a way. 

On a way you can still remove a node using `remove(nodeOrNodes)`.

I've published an new plugin version. Please update it in the JOSM preferences dialog.
