### ISSUE TITLE
Is it possible to simulate UI clicks?

### ISSUE THREAD

**Issue by bagage** [Gubaer/josm-scripting-plugin#48]
To interact with plugins which may not provide proper interface (non static methods mainly), I'd like to simulate click events on button instead.
Is there a way to do that?

Thanks!

**Comment by Gubaer** [comment]
You could try to get access to a Swing component used in  JOSM itself or in a plugin and then try to invoke UI actions on this component  - more about this on [stackoverflow](https://stackoverflow.com/questions/5109274/programmatically-clicking-a-gui-button-in-java-swing)

**Comment by SwiftFast** [comment]
I tried that, but due to JOSM's class structure I had trouble catching the components. I no longer remember fully, but I think the main frame, or one of the objects up the hierarchy, had private inaccessible objects, making it impossible to reach the components.

It could still be possible. Perhaps I missed something. Or maybe some JOSM patching (adding some more getters) could allow it.

**Comment by bagage** [comment]
@SwiftFast If you have any example of you did it, it would definitely help - I may add the missing getters on JOSM part for instance :).

**Comment by Gubaer** [comment]
I have to admit that I never did it myself! I only vaguely remembered that it could be done and thanks to google I ended up on [stackoverflow](https://stackoverflow.com/questions/5109274/programmatically-clicking-a-gui-button-in-java-swing) ...

**Comment by SwiftFast** [comment]
We'd need to obtain the Swing objects before that answer becomes useful.

@bagage I found this small comment I left for myself.  *assuming* mainMenu is the key to accessing the swing objects (I no longer remember if that's the case), then this is what's needed:

```
org.openstreetmap.josm.gui.MainApplication mainApplication = getMainApplicationSingletonSomeHow(); // how?
org.openstreetmap.josm.gui.MainFrame mainFrame = mainApplication.mainFrame; // won't work because it's private and has no public method
org.openstreetmap.josm.gui.MainMenu mainMenu = mainFrame.getMenu(); // works fine
```

I may look at the code and provide more accurate details later.

**Comment by Gubaer** [comment]
Just wondering. [SwiftFast](https://github.com/SwiftFast), [bagage](https://github.com/bagage), and friends seem to rely on the JOSM scripting plugin like nobody else did in the last couple of years. What are you guys up to? :-)

**Comment by bagage** [comment]
We're both unrelated (I think) so it's a coincidence :). I'm personally working on [buildings import in France](https://github.com/bagage/cadastre-conflation/tree/master/josm-scripts). Trying to automatizing the boring parts (configuring plugins by clicking on buttons, etc.).

**Comment by SwiftFast** [comment]
I am operating a very useful [editing bot](https://wiki.openstreetmap.org/wiki/User:SwiftFast#SwiftFast_bot) (and gradually expanding it). I am also considering writing a module that allows people to easily deploy mods.

We may have another problem: Let's assume we manage to access the components, it appears a script is fully blocking, meaning JOSM will not respond at all until the script is over. This may be acceptable for some cases, but not all cases. Sometimes you want the script to simulate a click, then wait for something, then click again. 

I tried bypassing this blocking for different purposes earlier, but since Rhino has no built-in setTimeout, getting things asynchronous was hard (it eventually worked via a custom setTimeout implementation but for some reason the java bindings were lost inside the setTimeout callback).

Lastly, One should ask: this is really needed? @bagage, buttons are for us inferior humans to use, our bot overlords should be able to do all things we do, but faster and without buttons. If you find yourself needing this, perhaps you're doing it the hard way, or perhaps we just need to expand the API.

**Comment by bagage** [comment]
>  @bagage, buttons are for us inferior humans to use, our bot overlords should be able to do all things we do, but faster and without buttons.
To be clearer, I need to use (others) plugins from JOSM. The main issue I see is that some of them do not share proper static API methods to be called, and I didn't found a way to use the instantiated action neither. 
I thought that clicking on buttons should be working "out-of-the-box", simply because it's what users would do. And I (as a script writter), don't have to deal with plugins API change (as soon as the UI does not change).

**Comment by bjohas** [comment]
Hi @bagage, I see you used 

var autoScaleAction = org.openstreetmap.josm.actions.AutoScaleAction; ... autoScaleAction.zoomToSelection();

Do you know how to zoom in more closely? I've tried a few things, like

org.openstreetmap.josm.actions.ZoomInAction();
org.openstreetmap.josm.gui.dialogs.SelectionListDialog.zoomToSelectedElement();
org.openstreetmap.josm.data.osm.visitor.BoundingXYVisitor.visit(pos);
org.openstreetmap.josm.data.osm.visitor.BoundingXYVisitor.enlargeBoundingBox(1.0);

but get errors about the methods not being found. I'm also interested in buildings, and faster ways of adding simple buildings.

**Comment by bagage** [comment]
@bjohas No idea, but the autoscaleAction class use some JOSM parameters to compute the boundingbox. If you can modify `zoom_to_selection_min_size_in_meter` parameter, maybe that could do the trick.

**Comment by bjohas** [comment]
@bagage - thanks! Do you mean the parameters that are in the advanced preferences? E.g. edit.zoom-enlarge-bbox affects autoScaleAction.zoomToSelection. I don't know how to set those parameters within the script though.

**Comment by bagage** [comment]
Since #71 I do not need anymore to simulate UI clicks since most of actions can be triggered programatically, so closing this
