### ISSUE TITLE
Referencing Groovy Scripts

### ISSUE THREAD

**Issue by drkludge** [Gubaer/josm-scripting-plugin#51]
I was interested in issue #43.  I tried loading Jar files on the JOSM command line via -cp.  I tried loading Jar files in the same location as the groovy script.  Is the [scripting environment](http://gubaer.github.io/josm-scripting-plugin/doc/scripting-environment.html) just for javascript?  Is there some other way to reference groovy scripts?

**Comment by Gubaer** [comment]
> Is the scripting environment just for javascript?

Yes. The [scripting environment](http://gubaer.github.io/josm-scripting-plugin/doc/scripting-environment.html) is part of the  **JavaScript** API. It doesn't apply to other supported scripting languages, in particular, it doesn't apply to Groovy

> Is there some other way to reference groovy scripts?

The main feature of  the scripting environment is a `require()` method which allows to load a JavaScript module. In Groovy this isn't necessary, because you can use Groovys [`import`](http://groovy-lang.org/structure.html#_imports) to "load" other Groovy packages or classes.
