### ISSUE TITLE
Always returning "package" by default?

### ISSUE THREAD

**Issue by bagage** [Gubaer/josm-scripting-plugin#70]
I'm trying to figure out why my script does not work:

Basically I have:

```java
public class TodoPlugin extends Plugin {
	public static final TodoDialog dialog = new TodoDialog();
        // some code
}
public class TodoDialog extends ToggleDialog {
	public void trigger() {
                actAdd.actionPerformed(null);
        }
    // some code
}
```
And I try to invoke it with the following js script:

```js
        var todoPlugin = org.openstreetmap.josm.plugins.todo.TodoPlugin;
        todoPlugin.dialog.trigger();
```

Which yields:

> Error message:TypeError: Cannot call property trigger in object [JavaPackage org.openstreetmap.josm.plugins.todo.TodoPlugin.dialog]. It is not a function, it is "object".

I do not understand what's wrong. But then, If I try to show what type of object `dialog` is, it always shows `package`, even if it does not exist and/or it should be `class/object`:

```sh
> josm.alert(org.openstreetmap.josm.plugins.todo.TodoPlugin)
[JavaPackage org.openstreetmap.josm.plugins.todo.TodoPlugin] // should be class TodoPlugin?
> josm.alert(org.openstreetmap.josm.plugins.todo.TodoPlugin.dialog)
[JavaPackage org.openstreetmap.josm.plugins.todo.TodoPlugin.dialog] // should be class TodoDialog? 
> josm.alert(org.openstreetmap.josm.plugins.todo.TodoPlugin.dialautiadtuiletdale)
[JavaPackage org.openstreetmap.josm.plugins.todo.TodoPlugin.dialautiadtuiletdale) // should be undefined or null or equivalent?
```

**Comment by qeef** [comment]
I have the same problem. Workaround is `josm.menu.get(4).getItem(0).doClick(1);` if the plugin creates menu item entry. I have small script here: https://gitlab.com/qeef/josm-scripts/blob/master/rebuilding.js

**Comment by bagage** [comment]
Unfortunately plugins I'd like to use only add a window and I'm not sure I can access theses. 

By the way I totally forgot about #48, but mainly that Josm [now loads plugin in separates classloaders](https://josm.openstreetmap.de/ticket/15218). I'll open another issue for that.

**Comment by Gubaer** [comment]
I can't reproduce this. When I execute the following JS fragment in the scripting console, everything looks fine. Does this work in your environment too? 

```javascript
var console = require("josm/scriptingconsole");

// get reference to a class and print it
var ScriptingPlugin = org.openstreetmap.josm.plugins.scripting.ScriptingPlugin;
console.println(ScriptingPlugin);
// -> [JavaClass org.openstreetmap.josm.plugins.scripting.ScriptingPlugin]

// get the content of a static final field and print it
console.println(ScriptingPlugin.START_MODULE_NAME );
// -> ScriptingPlugin_Start, as expected 

// invoke a static method, in this case replies the singleton plugin instance 
var instance = ScriptingPlugin.getInstance();
console.println(instance);
// -> org.openstreetmap.josm.plugins.scripting.ScriptingPlugin@b37da98
```

**Comment by Gubaer** [comment]
The Moziall Rhino Engine, which is shipped with the scripting plugin, tries to identify, whether an expression `a.b.c.d.FooBar` refers to a Java class `FooBar` in the Java package `a.b.c.d` or whether the same expression is equivalent to a sequence of property accesses `a["b"]["c"]["d"]["FooBar"]`.

For instance, if you execute the following fragment in the scripting console, an error is thrown:
```javascript
var x = a.b.c.FooBar;
// Results in: ReferenceError: "a" is not defined
```
In your case, the fully qualified class name for `TodoPlugin` starts with `org` and the scripting context in the scripting console already knows about an object `org` of type `JavaPackage` because all the JOSM classes start with  the prefix `org`. Access to a property `foo` of an object of type `JavaPackage` never results in `undefined`. For instance `openstreetmap` in `org.openstreetmap` or  `org["openstreetmap"]` respectively, is always considered to be a valid property by Rhino ([has() always returns true](https://github.com/mozilla/rhino/blob/d6dc98e5cfd25038d94d7642bc998abc478e6adb/src/org/mozilla/javascript/NativeJavaPackage.java#L63) in Rhinos implementation of a Java package).

Rhino tries its best to find out, what `org.openstreetmap` refers to. If [it can load a class](https://github.com/mozilla/rhino/blob/d6dc98e5cfd25038d94d7642bc998abc478e6adb/src/org/mozilla/javascript/NativeJavaPackage.java#L110) with this name, it assumes it is a java class. As a last resort, Rhino [creates a JavaPackage](https://github.com/mozilla/rhino/blob/d6dc98e5cfd25038d94d7642bc998abc478e6adb/src/org/mozilla/javascript/NativeJavaPackage.java#L140) `org.openstreetmap`.

In your case, for `org.openstreetmap.josm.plugins.todo.TodoPlugin`, 
* Rhino already knows, that `org`, `org.openstreetmap`, ..., `org.openstreetmap.josm` are Java packages
* when it looks up `org.openstreetmap.josm.plugins.todo` it creates a new Java package
* when it looks up `org.openstreetmap.josm.plugins.todo.TodoPlugin` it can't load the java class `org.openstreetmap.josm.plugins.todo.TodoPlugin` because it isn't accessible by the class loader for the scripting plugin. Rhino therefore creates yet another java package `org.openstreetmap.josm.plugins.todo.TodoPlugin` 

Dito then for `org.openstreetmap.josm.plugins.todo.TodoPlugin.dialog`
* since Rhino already assumes `org.openstreetmap.josm.plugins.todo.TodoPlugin` is a JavaPackage and since it can't load `org.openstreetmap.josm.plugins.todo.TodoPlugin.dialog` as java class, it assumes `org.openstreetmap.josm.plugins.todo.TodoPlugin.dialog` must be a Java package too.

**Comment by bagage** [comment]
Thanks for the detailed explanation (again!) @Gubaer.  Rhino interpretation of java packages seems a bit odd but I guess there is nothing much we can do about it... but it makes scripts writing a bit difficult! (specially due to JOSM class loader issue #71).

Maybe this could be written in the documentation so that people understand that "Package" means most of the time that nothing could be found?

**Comment by Gubaer** [comment]
You could load a Java Class using Javas `Class.forName(...)`.  This bypasses Rhino. If the class can be loaded, we get hold on a reference to the class; if not, this aproach throws an exception.
```javascript
var console = require("josm/scriptingconsole");
// this should work
var Main = java.lang.Class.forName("org.openstreetmap.josm.Main");
console.println("class Main: " + Main);

try {
    // this should fail and throw an exception
    var TodoPlugin = java.lang.Class.forName("org.openstreetmap.josm.plugins.todo.TodoPlugin");
} catch(e) {
   console.println(e);
  // -> JavaException: java.lang.ClassNotFoundException: org.openstreetmap.josm.plugins.todo.TodoPlugin
}
```

**Comment by bagage** [comment]
Ohhh, very nice! Indeed I'll update my script to load plugin that way, so that I get the information if plugin is installed or not (well, yet plugins are not found due to #71 obviously!). Thanks for the pointer @Gubaer, I believe this could be a final point to this issue!
