### ISSUE TITLE
Access to plugin class loader

### ISSUE THREAD

**Issue by bagage** [Gubaer/josm-scripting-plugin#71]
Since 1 year or so, [plugins are loaded separately from the core in a separate class loader](https://josm.openstreetmap.de/ticket/15218).

Could josm scripting plugin gives us access to plugin class loaders? (related to #70 #48)

**Comment by Gubaer** [comment]
Yes, I'll take care of it. Will have to investigate first how class loaders are now used in JOSM.

**Comment by bagage** [comment]
Hey @Gubaer, did you find anything interesting yet? Would be a very good news to hear :)!

**Comment by Gubaer** [comment]
I can execute this JavaScript fragment in the scripting console:
```javascript
var console = require("josm/scriptingconsole");
var scriptingPluginClass = java.lang.Class.forName(
    "org.openstreetmap.josm.plugins.scripting.ScriptingPlugin");
var scriptingPluginClassLoader = scriptingPluginClass.getClassLoader();
console.println("class loader for class 'ScriptingPlugin' is: " + scriptingPluginClassLoader);
```
> class loader for class 'ScriptingPlugin' is: PluginClassLoader [urls [file:/D:/software/josm/josm_home/plugins/scripting.jar]]

I can't get hold of the class loader of another plugin, though.
```javascript
var console = require("josm/scriptingconsole");
//!!! will throw !!!
var ContourMergePlugin =  java.lang.Class.forName(
    "org.openstreetmap.josm.plugins.contourmerge.ContourMergePlugin");
```

[This ticket](https://josm.openstreetmap.de/ticket/15218) suggest to make use of `PluginClassLoader.addDependency(PluginClassLoader other)` to add a dependency to another plugin. In fact, it is easy to get hold on the class loader of the scripting plugin, see above.  Unfortunately, there is no way to get hold on the class loader of another plugin **from within the scripting plugin**. 

```javascript
scriptingClassLoader.addDependency(/* what woud we add here? */);
```
Since some time, a plugin *can* declare a dependency to another plugin. If, for instance, the scripting plugin declared a dependency to the `contourmerge` plugin, the plugin class for the `contourmerge` plugin could be looked up from within the scripting plugin. In order to declare the dependency, it would have to add the property `Plugin-Requires` in the `META-INF/MANIFEST.MF` file of the plugin jar:
```properties
Plugin-Requires: contourmerge
```
When JOSM loads the main class of a plugin `P` it first [assembles a plugin class loader](https://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/plugins/PluginHandler.java#L833) which refers to child class loaders for other plugins `P` depends on. Then it [creates the one an only instance of the plugin using this carefully assembled class loader](https://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/plugins/PluginHandler.java#L768).

At this point JOSM would have to know, that your script is going to access another plugin from the scripting plugin. The dependency of your script would have to be turned into a general dependency for the scripting plugin. Thus, the `MANIFEST.MF` file in the scripting plugin jar would have to enumerate all the available plugins which a script might potentially need to access.

```properties
Plugin-Requires: contourmerge,anotherplugin,yetanotherplugin,.....
```
It would be nice, if the scripting plugin was loaded differently by JOSM than the other plugin.  It would be convenient, if it was loaded with a plugin class loader which includes **all** the locally available plugins as dependencies. As a consequence, [PluginHandler](https://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/plugins/PluginHandler.java) in JOSM would have to be changed.

Currently, I can't come up with an idea how to implement something like that just in the scripting plugin, without having to change the way, JOSM loads and instantiates plugins.

**Comment by don-vip** [comment]
Would `Plugin-Requires: all` work for you, if we implement this as an alias for "all other plugins"?

**Comment by bagage** [comment]
Would this means that all other plugins must be installed for this one to work, or could they be missing?

**Comment by don-vip** [comment]
You're right, it would require all plugins to be installed, so not a good idea.
We can add two methods:

1. a method that takes a plugin name and returns the classloader for that plugin and if that plugin is not installed, returns null
2. a method that takes a plugin name and prompts the user to install it if not already installed

If that's OK for you please create a new ticket on JOSM bugtracker (or better: submit a patch :) )

**Comment by floscher** [comment]
Wait a second, there's already
https://github.com/openstreetmap/josm/blob/147ffea86b2232497745211db45bf48783bd91ef/src/org/openstreetmap/josm/plugins/PluginHandler.java#L1207-L1220
```java
public static PluginClassLoader getPluginClassLoader(String name) { […] }
```

**Comment by bagage** [comment]
Well it seems we are on a good track, thanks @floscher! it kinda works:

```js
        var todoClassloader = org.openstreetmap.josm.plugins.PluginHandler.getPluginClassLoader("todo");
        todoClassloader.loadClass("org.openstreetmap.josm.plugins.todo.TodoDialog").actAdd.actionPerformed(); // properly instantiate a new todo dialog!
```

However it does not work when I add some static method into TodoPlugin.java and use that jar instead (compiled with `ant dist`), it seems the newly static fields/methods are not visible and I don't know why:

```java
public class TodoPlugin extends Plugin {
	public static final TodoDialog dialog = new TodoDialog();
	public static void foo() {
        System.out.println("lol!!!");
    }
    // normal code below ...
```

```
        var todoPlugin = todoClassloader.loadClass("org.openstreetmap.josm.plugins.todo.TodoPlugin");
        todoPlugin.dialog.trigger(); // fails because it cannot find dialog property of plugin
```

![image](https://user-images.githubusercontent.com/1451988/43610694-29929bd0-96a7-11e8-8447-a9b97fa03c7c.png)

**Comment by floscher** [comment]
@bagage You can try
```java
PluginHandler.getPluginClassLoader("todo")
  .loadClass("org.openstreetmap.josm.plugins.todo.TodoPlugin")
  .getDeclaredMethod("foo")
  .invoke(null);
```
Not the prettiest solution, but it should work.

**Comment by Gubaer** [comment]
@bagage 
> However it does not work when I add some static method into TodoPlugin.java and compile that JAR (with ant dist),

Did you make sure that the plugin is not only **built** but also **deployed** to the plugin subdirectory of `josm.home` where JOSM will pick it up and load it?

**Comment by bagage** [comment]
Yes indeed, nice reminder though I did copy the jar in ~/.local/share/JOSM/plugins right after compilation.

I finally got it working with the following code:

```
        var todoClassloader = org.openstreetmap.josm.plugins.PluginHandler.getPluginClassLoader("todo");
        // if todoClassloader is null, plugin is not installed
        var todoPlugin = todoClassloader.loadClass("org.openstreetmap.josm.plugins.todo.TodoPlugin");
        var dialog = todoPlugin.getDeclaredField('dialog').get(todoPlugin);

        var f = dialog.class.getDeclaredField('actAdd');
        f.setAccessible(true);
        f.get(dialog).actionPerformed(null)
```

I'm not sure why we need to access member properties via `getDeclaredField()` but at least this works :fireworks:. Thanks @Gubaer, @floscher and @don-vip here!

**Comment by Gubaer** [comment]
I've published a new release. It provides a new function `josm.loadClassFrom3dPartyPlugin()` to load a class from a 3d-party plugin.

```javascript
var console = require("josm/scriptingconsole");
var cls = josm.loadClassFrom3dPartyPlugin(
   "contourmerge",
   "org.openstreetmap.josm.plugins.contourmerge.ContourMergePlugin"
);
// isEnabled() is a static method of the class ContourMergePlugin
console.println(cls.isEnabled());
```
